// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_vmJJo80YfLvKX4vBdcsTW1GDSkBiJck',
    appId: '1:990087971485:web:36d50a2a570012c47e8a74',
    messagingSenderId: '990087971485',
    projectId: 'vida-activa-c08f9',
    authDomain: 'vida-activa-c08f9.firebaseapp.com',
    storageBucket: 'vida-activa-c08f9.firebasestorage.app',
    measurementId: 'G-RFRP2CT65V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDc3HYbAoSjRrrp8pt39hANGrts_UfUfc',
    appId: '1:990087971485:android:1e1a4d72897e3e457e8a74',
    messagingSenderId: '990087971485',
    projectId: 'vida-activa-c08f9',
    storageBucket: 'vida-activa-c08f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCft0stIq1Rbw6mh64F2pNLjdCZPxIF7F0',
    appId: '1:990087971485:ios:88cdef2d42836eee7e8a74',
    messagingSenderId: '990087971485',
    projectId: 'vida-activa-c08f9',
    storageBucket: 'vida-activa-c08f9.firebasestorage.app',
    iosBundleId: 'com.example.movementReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCft0stIq1Rbw6mh64F2pNLjdCZPxIF7F0',
    appId: '1:990087971485:ios:88cdef2d42836eee7e8a74',
    messagingSenderId: '990087971485',
    projectId: 'vida-activa-c08f9',
    storageBucket: 'vida-activa-c08f9.firebasestorage.app',
    iosBundleId: 'com.example.movementReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_vmJJo80YfLvKX4vBdcsTW1GDSkBiJck',
    appId: '1:990087971485:web:7dab05b75537174b7e8a74',
    messagingSenderId: '990087971485',
    projectId: 'vida-activa-c08f9',
    authDomain: 'vida-activa-c08f9.firebaseapp.com',
    storageBucket: 'vida-activa-c08f9.firebasestorage.app',
    measurementId: 'G-QGLER5H5ZK',
  );
}
